version: '3.8'

services:
  timetable-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tiet-timetable
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=production
    restart: unless-stopped