version: "3.8"

services:
  timetable-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tiet-timetable
    ports:
      - "8080:8080"
    environment:
      - APP_ENV=production
    restart: unless-stopped